name: restaurant
description: "A new Flutter project."
# Ligado a FIREBASE
# jottanewyork@gmail.com --- restaurant
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

  

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0 
  fluttertoast: ^8.2.4
  location:
  google_maps_flutter:
  pay: ^1.0.6
  velocity_x: 
  animated_splash_screen: ^1.3.0
  get: ^4.6.5
  get_it: ^7.6.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Circular Std
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 600
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/CircularStd-Black.otf
          weight: 800


  