// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEMBiAaBn4cjDqnlOBa4oHqvIuinqIIU',
    appId: '1:917348530341:web:d59fb110726ae095af754c',
    messagingSenderId: '917348530341',
    projectId: 'restaurant-b19b1',
    authDomain: 'restaurant-b19b1.firebaseapp.com',
    storageBucket: 'restaurant-b19b1.appspot.com',
    measurementId: 'G-20VKMGWP3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnB0-RxG-SSLt8bniAVIwTpOm0qtMUwk',
    appId: '1:917348530341:android:ebfd4fadc802af07af754c',
    messagingSenderId: '917348530341',
    projectId: 'restaurant-b19b1',
    storageBucket: 'restaurant-b19b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHT_ySSQKO4JkCDvEVEEDrJe96DNo-jNk',
    appId: '1:917348530341:ios:48afe6a4ea38ba92af754c',
    messagingSenderId: '917348530341',
    projectId: 'restaurant-b19b1',
    storageBucket: 'restaurant-b19b1.appspot.com',
    iosBundleId: 'com.johonbar.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHT_ySSQKO4JkCDvEVEEDrJe96DNo-jNk',
    appId: '1:917348530341:ios:c1e5dde20b9eff4aaf754c',
    messagingSenderId: '917348530341',
    projectId: 'restaurant-b19b1',
    storageBucket: 'restaurant-b19b1.appspot.com',
    iosBundleId: 'com.johonbar.restaurant.RunnerTests',
  );
}
